name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths-ignore:
      - "**.md"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Prepare gradle.properties
        run: |
          mkdir -p $HOME/.gradle
          echo "repoUsername=${{ secrets.DIVERPG_DEPLOY_USERNAME }}" >> $HOME/.gradle/gradle.properties
          echo "repoPassword=${{ secrets.DIVERPG_DEPLOY_PASSWORD }}" >> $HOME/.gradle/gradle.properties
      - name: Deploy
        run: |
          chmod 775 ./gradlew
          ./gradlew clean test publish